import { useContext } from "react"
import "./recipt.scss"
import TransContext from "../../context/transContext";

const Recipt = ({invoice}) => {
  const data=useContext(TransContext);
  const inputs=data.state;
  let val=0;
  const next=()=>{
    val=val+1;
    return val+"fhjhf"
  }
  return (
    <div className="recipt">
      <div className="top">
        <div className="heading">
          <h1>INVOICE</h1>
          <img src="https://ouch-cdn2.icons8.com/idtJ-at3f0b7VYPTh85GzmiRzEMTr_eQMLbfQxOnn98/rs:fit:408:400/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvNTk5/LzA0MjcwZTBjLTkz/MjAtNDAyNi05OTc3/LTAwOTE3NDcwOGQ0/Yy5wbmc.png" alt=""/>
        </div>
        <div className="invoiceInfo">
          <div className="invoiceTo">
            <p>Invoice To :</p>
            <h3>{inputs.customerName}</h3>
          </div>
          <div className="invoiceDet">
            <p>Invoice Date:</p>
            <span>{`${new Date().getDate()}/${new Date().getMonth()}/${new Date().getFullYear()}`}</span>
            <p>Invoice No: <strong>{inputs.invoiceNo}</strong></p>
          </div>
        </div>
      </div>
      <hr/>
      <div className="middle">
        <div className="productHeader">
          <span className="productTitle">PRODUCT</span>
          {inputs.products.map(x=>
            <span className="product" key={next()}>{x.productName}</span>
          )}
        </div>
        <div className="productHeader">
          <span className="productTitle">PRICE</span>
          {inputs.products.map(x=>
            <span className="product" key={next()}>{x.price}</span>
          )}
        </div>
        <div className="productHeader">
          <span className="productTitle">QTY</span>
          {inputs.products.map(x=>
            <span className="product" key={next()}>{x.quantity}</span>
          )}
        </div>
        <div className="productHeader">
          <span className="productTitle">TOTAL</span>
          {inputs.products.map(x=>
            <span className="product" key={next()}>{x.total}</span>
          )}
        </div>
      </div>
      <hr/>
      <div className="bottom">
        <div className="total">
            <span className="totalAmt"><b>TOTAL AMOUNT : </b></span>
            <span className="totalAmt price"> &#8377; {inputs.totalPrice}</span>
            <hr id="innerHr"/>
        </div>
        <div className="extraInfo">
          <hr/>
          <h1>Bill Generated By Prime Sales and Service</h1>
          <div className="details">
            <div className="bank">
              <h4>Bank Details</h4>
              <div className="bankInfo">
                <span><b>Bank:</b> Vijaya Bank</span>
                <span><b>A/c No:</b> 850100301000172</span>
                <span><b>IFSC Code:</b> VIJB0008501</span>  
              </div>
            </div>
            <div className="address">
              <h4>Address</h4>
              <span>Forth Furlong Point, Polo, Shillong-01</span>
            </div>
            <div className="contact">
              <h4>Contact Us</h4>
              <div className="contactDetails">
                <span><b>Email: </b>ayush90xy@gamil.com</span>
                <span><b>Phone: </b>7085577356/8258061243</span>  
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Recipt